### ISSUE TITLE
PioTek FAM-USB 515 device_type

### ISSUE THREAD

**Issue by legnad** [grimmpp/home-assistant-eltako#112]
I just received a new PioTek FAM-USB 515 and am unsure which setting to use for `device_type` in the yaml-`eltako:` section. I already hjave a FGW14-USB configured and running successfully and want to use the FAM-USB 515 as a second gateway (mostly to teach the FUTH 230V thermostat devices).

For now I've tested it with `device_type: "enocean-usb300"` which seems to work. Maybe this could be mentioned in the docs.

Ganz dickes Lob übrigens! Echt gute Arbeit!

**Comment by grimmpp** [comment]
Please, have a look into the docs [here](https://github.com/grimmpp/home-assistant-eltako/tree/main/docs/gateways) there is an example at the end. 

Maybe this helps as well: https://github.com/grimmpp/home-assistant-eltako/tree/main/docs/gateway_usage

Sometimes the MGW / FAM-USB515 is a bit petulant when it comes to fast connection changes. It helps to power it off and on again.

**Comment by grimmpp** [comment]
So there was a bug in getting the base id which was requested in the process of creating the connection. ... fixed it on main but haven't released it yet. Can you test it?

**Comment by legnad** [comment]
I do not have connection issues. I've created this issue solely for the people who try to use the FAM-USB515 and do not know how to set it up.

The only problem is that the docs are missing the mention of the `device_type` key/value to use in the YAML. The examples do not mention that.

As mentioned in the original issue, I've tested with `device_type: "enocean-usb300"` and it seems to work so far.

Off-Topic:

I also have a FMZ14 and a F2L14 device ready but not integrated into HA yet and also have a FSB61 lying around waiting to be installed.

To give some more context I can happily provide my configuration just for reference and if people are looking for further examples. Everything works as expected:

`  gateway:
  - id: 1
    base_id: FF-AA-80-00 # Eltako FGW14-USB # /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AB0P0ZI2-if00-port0
    device_type: fgw14usb
    devices:
        binary_sensor: # testing
        - id: FE-D8-33-09 # Taster Arbeitszimmer Licht
          eep: F6-02-01
        sensor:
        - id: FF-CD-01-92
          eep: A5-10-12
          name: "Arbeitszimmer Temperatur & Luftfeuchte"
        - id: FF-BC-01-12
          eep: A5-10-12
          name: "Schlafzimmer Temperatur & Luftfeuchte"
        - id: FF-AC-9D-12
          eep: A5-10-12
          name: "Kinderzimmer Temperatur & Luftfeuchte"
        - id: FF-DB-A6-92
          eep: A5-10-12
          name: "Bibliothek Temperatur & Luftfeuchte"
        light:
    # FUD 14 Adr. 12 (Funktion 32)
        - id: 00-00-00-0C 
          eep: A5-38-08
          name: "Arbeitszimmer Dimmer"
          sender:
            id: 00-00-B0-0C
            eep: A5-38-08
    # FUD 14 Adr. 10 (Funktion 32)
        - id: 00-00-00-0A
          eep: A5-38-08
          name: "Schlafzimmer Dimmer"
          sender:
            id: 00-00-B0-0A
            eep: A5-38-08
    # FUD 14 Adr. 11 (Funktion 32)
        - id: 00-00-00-0B
          eep: A5-38-08
          name: "Kinderzimmer Dimmer"
          sender:
            id: 00-00-B0-0B
            eep: A5-38-08
    # FSR 14 Adr. 15-18 Kanal 1 (Funktion 51)
        - id: 00-00-00-0F
          eep: M5-38-08
          name: "Bibliothek Licht"
          sender:
            id: 00-00-B0-0F
            eep: A5-38-08
    # FSR 14 Adr. 19-22 Kanal 1 (Funktion 51)
        - id: 00-00-00-13
          eep: M5-38-08
          name: "Badezimmer Licht"
          sender:
            id: 00-00-B0-13
            eep: A5-38-08
    # Kanel 3 (LED Panel)
        - id: 00-00-00-15
          eep: M5-38-08
          name: "Badezimmer LED Panel (Eltako)"
          sender:
            id: 00-00-B0-15
            eep: A5-38-08
            
    # FSR 14 Adr. 19-22 Kanal 4 (Funktion 51)
        - id: 00-00-00-16
          eep: M5-38-08
          name: "Flur Licht"
          sender:
            id: 00-00-B0-16
            eep: A5-38-08
        cover:
    # FSB14 Adr. 1-2 Kanal 1 (Funktion 31)
        - id: 00-00-00-01
          eep: G5-3F-7F
          name: "Schlafzimmer Rolladen"
          sender:
            id: 00-00-B0-01
            eep: H5-3F-7F
          device_class: shutter
          time_opens: 22
          time_closes: 20
    # FSB14 Adr. 1-2 Kanal 2 (Funktion 31)
        - id: 00-00-00-02
          eep: G5-3F-7F
          name: "Kinderzimmer Rolladen"
          sender:
            id: 00-00-B0-02
            eep: H5-3F-7F
          device_class: shutter
          time_opens: 22
          time_closes: 20
    # FSB14 Adr. 4-5 Kanal 1 (Funktion 31)
        - id: 00-00-00-04
          eep: G5-3F-7F
          name: "Arbeitszimmer Rolladen"
          sender:
            id: 00-00-B0-04
            eep: H5-3F-7F
          device_class: shutter    
          time_opens: 22
          time_closes: 20
    # FSB14 Adr. 6-7 Kanal 1 (Funktion 31)
        - id: 00-00-00-06
          eep: G5-3F-7F
          name: "Bibliothek Rolladen"
          sender:
            id: 00-00-B0-06
            eep: H5-3F-7F
          device_class: shutter      
    # FSB14 Adr. 6-7 Kanal 2 (Funktion 31)
        - id: 00-00-00-07
          eep: G5-3F-7F
          name: "Küche Rolladen"
          sender:
            id: 00-00-B0-07
            eep: H5-3F-7F
          device_class: shutter   
  - id: 2
    base_id: FF-9F-5E-80 # PioTek FAM-USB 515 # /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AB0P4TMI-if00-port0
    device_type: "enocean-usb300"
    devices:
        #light:
        ## FUD 14 Adr. 12 (Funktion 32)
        #- id: FF-E9-20-8C
        #  eep: A5-38-08
        #  name: "Arbeitszimmer Dimmer 2"
        #  sender:
        #    id: FF-9F-5E-8C
        #    eep: A5-38-08
        climate:
        
        - id: FF-E9-20-9B # Heizaktor Schlafzimmer
          eep: A5-10-06
          temperature_unit: "°C"
          name: "Schlafzimmer Thermostat"
          sender:
            id: FF-9F-5E-9B # Sender = FAM-USB + Heizaktor-Adresse
            eep: A5-10-06
          thermostat:
            id: FF-BC-01-01 # Wandthermostat Kinderzimmer
            eep: A5-10-06
        
        - id: FF-E9-20-9C # Heizaktor Kinderzimmer
          eep: A5-10-06
          temperature_unit: "°C"
          name: "Kinderzimmer Thermostat"
          sender:
            id: FF-9F-5E-9C # Sender = FAM-USB + Heizaktor-Adresse
            eep: A5-10-06
          thermostat:
            id: FF-AC-9D-01
            eep: A5-10-06
            
        - id: FF-E9-20-9D # Heizaktor Arbeitszimmer
          eep: A5-10-06
          temperature_unit: "°C"
          name: "Arbeitszimmer Thermostat"
          sender:
            id: FF-9F-5E-9D # Sender = FAM-USB + Heizaktor-Adresse
            eep: A5-10-06
          thermostat:
            id: FF-CD-01-81
            eep: A5-10-06
            
        - id: FF-E9-20-9E # Heizaktor Bibliothek
          eep: A5-10-06
          temperature_unit: "°C"
          name: "Bibliothek Thermostat"
          sender:
            id: FF-9F-5E-9E # Sender = FAM-USB + Heizaktor-Adresse
            eep: A5-10-06
          thermostat:
            id: FF-DB-A6-81
            eep: A5-10-06
`
