### ISSUE TITLE
Support for  EEP A5-10-03 (Temp. Sensor, Set Point Control)

### ISSUE THREAD

**Issue by schlegel** [grimmpp/home-assistant-eltako#119]
Could you please add support for EEP A5-10-03 (Temp. Sensor, Set Point Control). I think it's very similar to A5-10-06.

**Comment by grimmpp** [comment]
Yes, I can do. What device are you using? Is it maybe FTR78S? Then it would get hard for me to test because it is not available anymore. In this case I would need your test cooperation.

**Comment by grimmpp** [comment]
EEP A5-10-03 exists now: https://github.com/grimmpp/eltako14bus/blob/96eb2bb1407e7d98e84936e6749f34492f1f5807/eltakobus/eep.py#L646

Big question is what do you want to do with it in HA? I assume target temperature synchronization won't work with that device. So I see two cases:
1. displaying the current temperature
2. having a decoupled HA widget for controlling the target temperature independently from the FTR8S

**Comment by grimmpp** [comment]
A5-10-03 is now available in the [feature-branch](https://github.com/grimmpp/home-assistant-eltako/tree/feature-branch) as sensor. If you deploy this branch to your HA you can the configure the thermostat as sensor. You just need to specify id and eep then one device with to entries (target and current temperature) will be generated. 

[Here](https://github.com/grimmpp/home-assistant-eltako/blob/main/docs/install-specific-version-or-branch.md) is how to install another branch or tag. Just use `feature-branch` for checkout command.

**Comment by schlegel** [comment]
wow, that was fast! I have SR07 P devices which communicate with my eltako devices (https://www.thermokon.de/direct/products/sr07-p-temp-reinweiss-glaenzend). Currently I get current temperature and a percentage of the setpoint.

**Comment by grimmpp** [comment]
and what do you want to do with it in HA?

**Comment by schlegel** [comment]
the setpoint is used for a dashboard to monitor all rooms as my kid loves to turn all knobs

**Comment by schlegel** [comment]
I can confirm the temperature and setpoint is working. thanks a lot !
