### ISSUE TITLE
Integration of FMZ14 (Timer Relay)

### ISSUE THREAD

**Issue by magic2910** [grimmpp/home-assistant-eltako#127]
Hello,
could you add the Eltako FMZ14?
Switching is not possible, but you get the answer correct in HA.

Thanks in advance!

**Comment by grimmpp** [comment]
It should actually work if you configure it the same way like FSR14

**Comment by magic2910** [comment]
It is configured the same way (via enocean device manager)
            # Relay
            # Related devices: FTS14EM Button 00-00-10-01 (Type: FTS14EM Button, Adr: 00-00-10-01)
          - id: 00-00-00-23
            name: FMZ14 00-00-00-23
            eep: M5-38-08
            sender:
              id: 00-00-B0-23
              eep: A5-38-08

But switching via HA is not working, the status is shown correct (if I turn it on via Button - FTS14EM)

Or did you mean an other way?

Thanks!

**Comment by grimmpp** [comment]
looks actually good. Is the sender id 00-00-B0-23 registered in FMZ14 device with function key 51?

**Comment by magic2910** [comment]
> looks actually good. Is the sender id 00-00-B0-23 registered in FMZ14 device with function key 51?
Yes
![image](https://github.com/user-attachments/assets/cdb1f9ce-94ea-4851-a856-7b0fa3d5fd51)

**Comment by grimmpp** [comment]
That's how I thought it should work. Give me a few days time. I will check how I configured my one.

**Comment by grimmpp** [comment]
I will change eo_man so that it will automatically propose sender eep F6-02-01 for now you can simply change it on the right (detail view)

**Comment by magic2910** [comment]
Thank you! Now I can switch it via Home Assistant!
One more question, which function (Bottom rotary switch) did you choose?
I am using RV but the FMZ14 only times with the physical button (FTS14EM) pressed. If I switch it on via Home Assistant it keeps on, also switch off does not work via Home Assistant.
Thank you!

**Comment by grimmpp** [comment]
I've got confirmation from Eltako. Controller like HA are not supported. Software of FMZ is quite old. Alternatively, you could use a FSR which has almost the same functions.
Regarding configuration: I would try to use the rotary switchs and press the Button in HA to teach it in so you can decide what function should be used.
Please, let us know if it worked.

**Comment by magic2910** [comment]
Unfortunately the same behavior. I can switch the FMZ14 on via HA but the timer does not work. Switching off via HA is also not possible. Using a button via FTS14EM works fine. I will switch to an FSR14-2x and use HA for the timing function.

**Comment by grimmpp** [comment]
Hello @magic2910, so I tested a bit and it is still confusing to me. I managed to make it work in the usual way I do it. But it only worked the first time is used it for the classical "off-delay" function. Other functions work better ;-) 
However, I found a way how it works for me which is quite simple. Just change the `sender id` in the config. In my case I change it to `00-00-10-0A`. It looks like the actuator is reacting on a special range of ids!?

In such cases you can also approach the Eltako technology support. They are really good, supportive and have a lot of expertise. technik-beratung@eltako.de +49 (0) 711 94350002

**Comment by magic2910** [comment]
I think my problem is that I am using an physical button and a virtual switch for this. I will reach Eltako, maybe they have an other idea. 
Btw Sender ID switch changed nothing for me, works also the same way with your ID

**Comment by grimmpp** [comment]
Sometimes the logic/software version of the devices differs a bit. 
In the new release [0.1.34](https://github.com/grimmpp/enocean-device-manager/releases/tag/v0.1.34) of eo_man you can choose the template for FMZ and writing the sender into the device works now as well, at least on my end 🙈.
