### ISSUE TITLE
Setup failed for custom integration 'eltako' after Update 2024.09

### ISSUE THREAD

**Issue by kimzeuner** [grimmpp/home-assistant-eltako#129]
Today i had a problem after i updated HAOS to 2024.09.
After the restart my HA reported "Setup failed for custom integration 'eltako': Requirements for eltako not found: ['esp2-gateway-adapter==0.2.6]." and the integration didn`t start.
What i have done was 
1. Update the esp2-gateway-adapter to newest version 0.2.10 and changed the requirements in the manifest.json to esp2-gateway-adapter==0.2.10. The result was the same failure "Setup failed for custom integration 'eltako': Requirements for eltako not found: ['esp2-gateway-adapter==0.2.10."
2. Then changed the requirement to esp2-gateway-adapter>=0.2.6. Still the same issue.
3. Finally changed the requirement to esp2-gateway-adapter without any version. After a restart everything seems to work again.

Don`t know if it is an integration or HA issue but maybe it helps if anyone has the same issue and is searching for a solution.

**Comment by Stroett** [comment]
At least same issue. After updating HA to 2024.09 and HACS to 2.0.1.
So far no recovery found.

**Comment by kimzeuner** [comment]
Oh you are right, i have also updated HACS before and made the restart after the HAOS update so not sure if it came from the HACS or HAOS update.
Did you already try to go to custom/components/eltako and make the described changes (delete "==0.2.6" behind esp2-gateway-adapter) in the line requirements ?

**Comment by Stroett** [comment]
No. I will check it tonight when my kids are sleeping.

**Comment by Chrisego2** [comment]
At least same issue. After updating HA to 2024.09
Since I'm pretty new to HA, can anyone give a hand how to _change the requirement to esp2-gateway-adapter_

**Comment by kimzeuner** [comment]
Sure, you will need vidual studio code or file editor addon for this (file editor is easier for the start i think). So after you have installed the File Editor addon start and open it. Ine the upper left corner you find a folder symbol. Here you go to custom_components/eltako and look for the manifest.json file. Open it and you will find a line with "requirements: ..." there you have to make the changes. Save the file with the red symbol (i think its a floppy disk) in the top bar and restart Homeassistant.

**Comment by FMDHET** [comment]
By removing the version in the manifest.json, the integration is installing the old version 0.1 instead of 0.2.10
![esp2-gateway-adapter_0 1](https://github.com/user-attachments/assets/672692d8-9b8e-4b59-aa4f-2e769e9eafc9)

**only for homeassistant docker-version with root access:**
1. To fix this bug, you can enter via putty into your homeassistant docker ("docker exec -it homeassistant bash").
2. Than install esp2-gateway-adapter with "pip3 install esp2-gateway-adapter=0.2.10"
3. check the installed version with "pip3 list | grep esp2"

**Comment by kimzeuner** [comment]
I am using HAOS as a Virtual Machine in Proxmox. 
I have just checked the version of the esp2-gateway-adapter:
![image](https://github.com/user-attachments/assets/05a7c383-aa8d-47e4-a79e-3aa8834eddbc)
When i just use the Terminal Addon and check the version it says it is 0.2.10 but when i first use "docker exec -it homeassistant bash" and then check the version it says it is 0.1 so i'm not sure what is correct now.
After using your mentioned command "pip3 install esp2-gateway-adapter==0.2.10" and a HA restart it stays in version 0.2.10 in both variants and the integration seems to work fine too. 
Would you suggest to change the requirements back to "esp2-gateway-adapter>=0.2.6" or "esp2-gateway-adapter==0.2.10" or is that not relevant ?

**Comment by schlegel** [comment]
<img width="1395" alt="Screenshot 2024-09-07 at 13 23 05" src="https://github.com/user-attachments/assets/b6d933f8-f706-4210-a514-4fc342d304ce">
So I'm not alone with the problem after updating home assistant? Can I somehow solve the issue without going back in the version?

**Comment by schlegel** [comment]
@grimmpp Would it be possible that you release a new version of esp2-gateway-adapter which resolve the dependency issue? I would be extremely grateful :)

**Comment by schlegel** [comment]
dirty workaround: 
1. copy the 2 source files from the gateway adapter into the eltako component (https://github.com/grimmpp/esp2_gateway_adapter/tree/main/src)
2. in the component, edit the imports  in gateway.py (has to be "from .esp3_tcp_com import TCP2SerialCommunicator" and "from .esp3_serial_com import ESP3SerialCommunicator") 
3. in the manifest json, include the requirements from the gateway adapter and set no version to PyYAML and zeroconf (those seem to be the problem) --> "requirements": ["eltako14bus==0.0.59", "enocean==0.60.1", "StrEnum", "aiocoap==0.4.7", "pyserial==3.5", "pyserial-asyncio==0.6", "PyYAML", "zeroconf"]

**Comment by grimmpp** [comment]
Currently looking into it but haven't found the root cause. Leaving the Version unspecified would cause other problems. 
Will Take some time because i'm currently in vacation travelling.

**Comment by chef2gare** [comment]
hello guys,

I think it comes from this :
https://www.home-assistant.io/changelogs/core-2024.9
-> Bump zeroconf to 0.133.0 

esp2-gateway-adapter requires zeroconf==0.132.2

here is what is happenning in my container if I install it :
```
ccbd01c6ed38:~# pip install esp2-gateway-adapter==0.2.6
Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
Collecting esp2-gateway-adapter==0.2.6
  Downloading esp2_gateway_adapter-0.2.6-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: eltako14bus>=0.0.46 in /usr/local/lib/python3.12/site-packages (from esp2-gateway-adapter==0.2.6) (0.0.53)
Requirement already satisfied: enocean>=0.60.1 in /usr/local/lib/python3.12/site-packages (from esp2-gateway-adapter==0.2.6) (0.60.1)
Requirement already satisfied: pyserial in /usr/local/lib/python3.12/site-packages (from esp2-gateway-adapter==0.2.6) (3.5)
Requirement already satisfied: pyserial-asyncio in /usr/local/lib/python3.12/site-packages (from esp2-gateway-adapter==0.2.6) (0.6)
Requirement already satisfied: aiocoap in /usr/local/lib/python3.12/site-packages (from esp2-gateway-adapter==0.2.6) (0.4.11)
Collecting zeroconf==0.132.2 (from esp2-gateway-adapter==0.2.6)
  Downloading https://wheels.home-assistant.io/musllinux-index/zeroconf-0.132.2-cp312-cp312-musllinux_1_2_aarch64.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 24.1 MB/s eta 0:00:00
Requirement already satisfied: ifaddr>=0.1.7 in /usr/local/lib/python3.12/site-packages (from zeroconf==0.132.2->esp2-gateway-adapter==0.2.6) (0.2.0)
Requirement already satisfied: enum-compat>=0.0.2 in /usr/local/lib/python3.12/site-packages (from enocean>=0.60.1->esp2-gateway-adapter==0.2.6) (0.0.3)
Requirement already satisfied: beautifulsoup4>=4.3.2 in /usr/local/lib/python3.12/site-packages (from enocean>=0.60.1->esp2-gateway-adapter==0.2.6) (4.12.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/site-packages (from beautifulsoup4>=4.3.2->enocean>=0.60.1->esp2-gateway-adapter==0.2.6) (2.6)
Downloading esp2_gateway_adapter-0.2.6-py3-none-any.whl (9.3 kB)
Installing collected packages: zeroconf, esp2-gateway-adapter
  Attempting uninstall: zeroconf
    Found existing installation: zeroconf 0.133.0
    Uninstalling zeroconf-0.133.0:
      Successfully uninstalled zeroconf-0.133.0
Successfully installed esp2-gateway-adapter-0.2.6 zeroconf-0.132.2
```

**Comment by grimmpp** [comment]
I've created a new release containing all other changes made in between as well. Can you please test version 1.5.8

**Comment by kimzeuner** [comment]
For me everything seems to work fine with this version. No error on installation and the esp2-gateway-adapter was updated to 0.2.11.
![image](https://github.com/user-attachments/assets/bbe71cd9-f819-4202-9b65-f2999fe4bbb9)

**Comment by ceeekar** [comment]
I also can confirm that everything is running.

I'm not sure if this is related to the update or has been an issue before that:
In the logs I get an error at startup concerning the gateway as well as every cover and an error in the UI when trying to set a specific position if the shutter has not been moved to fully open or fully closed.
The position on all shutters is unknown at startup but gets updated once a shutter has been closed or opened. After that the positioning of a shutter seems to work an no error is presented in the UI.

[eltako_error.txt](https://github.com/user-attachments/files/16966495/eltako_error.txt)
note: addresses have been redacted

**Comment by schlegel** [comment]
> I've created a new release containing all other changes made in between as well. Can you please test version 1.5.8

thanks!

**Comment by grimmpp** [comment]
> I also can confirm that everything is running.
> 
> I'm not sure if this is related to the update or has been an issue before that: In the logs I get an error at startup concerning the gateway as well as every cover and an error in the UI when trying to set a specific position if the shutter has not been moved to fully open or fully closed. The position on all shutters is unknown at startup but gets updated once a shutter has been closed or opened. After that the positioning of a shutter seems to work and no error is presented in the UI.
> 
> [eltako_error.txt](https://github.com/user-attachments/files/16966495/eltako_error.txt) note: addresses have been redacted

That comes with new feature because the variable was not known before. It should only appear once after the update.
