### ISSUE TITLE
Error message "unit changed" since HA 2024.10

### ISSUE THREAD

**Issue by LutzDi** [grimmpp/home-assistant-eltako#132]
Good morning everybody,

I recently updated to HA 2024.10.1 and I experienced an error that the unit of the sensor *received_messages_per_session of my gateway was changed from "messages" to "". Please refer to the following screenshot, please excuse that it's in German:

<img width="459" alt="image" src="https://github.com/user-attachments/assets/d0603460-887c-4bf3-b11a-eb96095e7952">

Does anybody have an idea of what the reason is and what to do? I'm struggling that the new unit should be empty. I would appreciate any idea of what to do to solve this error. I'm not as familiar with HA, just new to this stuff... :)

Thx a lot for your help, enjoy your day...

Cheers
Lutz

**Comment by factor4** [comment]
Hi, I also did the update to 2024.10.1 right now. I did not got the error message you posted, but this Entity is completely gone:
<img width="582" alt="grafik" src="https://github.com/user-attachments/assets/9186e046-60d2-4ae0-8a83-c7676a2f782f">
Since I don't know what to do with this counter I don't care. I think you could do the same and clean up some space. ;)

**Comment by LutzDi** [comment]
Hi @factor4,

thx for your answer... You pointed me to an idea: The count only of this sensor is enough for everything we need. Yes, you are sure, that at the moment I don't know what to do with the value - but who knows what's coming up... I thought twice about this issue and I concluded that the value without unit is enough because the unit isn't needed. It's only a count...

And because I want to learn and understand all that stuff better and better I'm willing to clear such things, also if the are unimportant...

jfyi: The sensor is available in my HA and it's counting... I only mention this because you don't have this sensor anymore...

I would close the issue now...

Cheers
Lutz
