### ISSUE TITLE
Add F6-03 Rocker Switch, 4 Rocker

### ISSUE THREAD

**Issue by Zeusur** [grimmpp/home-assistant-eltako#134]
Please add F6-03-01 and F6-03-02

I want to add the Profile Button.

https://www.eltako.com/fileadmin/downloads/de/_bedienung/TF-4PT55_30000431-1_dt.pdf

**Comment by grimmpp** [comment]
Hello @Zeusur, 

are you sure it is not F6-02-01 and F6-02-02 what you mean? I don't find any new EEPs in this direction.
