### ISSUE TITLE
Initial setup: No gateway configuration available. Enter gateway into '/homeassistant/configuration.yaml'.

### ISSUE THREAD

**Issue by LHBL2003** [grimmpp/home-assistant-eltako#38]
I would like to switch from FHEM / ioBrocker to HomeAssistant. I am therefore currently checking my relevant integrations. I have successfully tested Alexa, Hue, Homatic, etc. Only with Eltako do I fail at the simplest step. 

First of all: My Eltako enocean 14 system is running under FHEM on a Respbarry Pi 4. I have only repositioned the USB cable from the FGW14-USB to the HomeAssistant (Pi 5). 
I have rebooted the HomeAssistant Pi to ensure that the USB interface is recognized.

I have integrated home-assistant-eltako via HACS.
I click on Add integration, select Eltako and immediately get this error message:
![image](https://github.com/grimmpp/home-assistant-eltako/assets/46369917/fbe95eae-b3d7-4086-97ad-877423dde231)

![image](https://github.com/grimmpp/home-assistant-eltako/assets/46369917/f4911dd4-e1da-4daa-852e-fe8f8404cc20)

`
Logger: eltako
Source: custom_components/eltako/config_helpers.py:112
Integration: Eltako ([documentation](https://github.com/grimmpp/home-assistant-eltako), [issues](https://github.com/grimmpp/home-assistant-eltako/issues))
First occurred: 12:28:06 (2 occurrences)
Last logged: 12:28:06

No `eltako:` key found in configuration.yaml.
`

I ignore the message and select the first or even the second entry and get this error message:
Whereby I believe that "usb-FTDI_FT232R_USB_UART_AK05EMVN-if00-port0" is surely the recommended entry? (Is both port 0)
(I have allegedly not filled in all mandatory fields.)
![image](https://github.com/grimmpp/home-assistant-eltako/assets/46369917/24682272-7614-4d9c-8078-398cd1f93949)

I then searched for a sample configuration and found this:
https://github.com/grimmpp/home-assistant-eltako/blob/main/docs/update_home_assistant_configuration.md

If I add this part to the configuration file "configuration.yaml" the YAML checkpoint is still ok, but I still can't set up the integration.

![image](https://github.com/grimmpp/home-assistant-eltako/assets/46369917/4168b244-288f-4559-b3cf-367d9338bdf8)

If I add at least the gateway entry, then I get problems with the YAML check.
Because I don't have any integration yet.

![image](https://github.com/grimmpp/home-assistant-eltako/assets/46369917/27a9f59c-19e9-4911-b7d7-81d95139c4b5)

![image](https://github.com/grimmpp/home-assistant-eltako/assets/46369917/049b2f66-a902-4229-abef-8f14de47c1eb)

Am I doing something wrong or is this a bug during the initial setup on a new system?
Because I can't complete step 2 of 3 from the installation and configuration documentation

**Comment by grimmpp** [comment]
Hello @LHBL2003,

that was already close. The `gateway` must be on the same level like `general_settings` and under devices must be at least one device like a light listed.

The following should work and create one light entry. Even if that is not correct the switch just would do nothing and jump back in HA.

```
eltako:
  gateway:
  - id: 1
    base_id: FF-AA-80-00
    device_type: fgw14usb
    devices: 
      light:
      - id: 00-00-00-01
        eep: M5-38-08
        name: FSR14_4x - 1
        sender:
          id: 00-00-B0-01
          eep: A5-38-08   
```

You can also try to generate a configuration. Unfortunately, not everything can right now be generated and you need to adjust some little things. 
https://github.com/grimmpp/home-assistant-eltako/tree/main/eltakodevice_discovery

**Comment by LHBL2003** [comment]
OK the indenting at the same level was my mistake / vscode error. :P
The dummy example was helpful.

![image](https://github.com/grimmpp/home-assistant-eltako/assets/46369917/b2b03570-30a1-4fe0-ad43-5273a27d035d)

I later saw the ID 1 and 2 in the documentation, but I ignored it because I only had one USB device. (See also [multiple gateway support](https://github.com/grimmpp/home-assistant-eltako/tree/main/docs/multiple-gateway-support/readme.md))

I had used this example as a guide. But it had 2 errors. Is this probably out of date?
[Example Configuration File](https://github.com/grimmpp/home-assistant-eltako/blob/main/docs/update_home_assistant_configuration.md#example-configuration-file)

-------------------------------------------
I was able to avoid Line 107 by deleting the part.
![image](https://github.com/grimmpp/home-assistant-eltako/assets/46369917/20257f56-e394-47cf-9937-6e141d729ff8)

Konfigurationswarnungen
Invalid config for 'eltako' at configuration.yaml, line 107: required key 'temperature_unit' not provided
Invalid config for 'eltako' at configuration.yaml, line 22: 'device' is an invalid option for 'eltako', check: eltako->gateway->0->device
Invalid config for 'eltako' at configuration.yaml, line 22: required key 'id' not provided**

-----------------------------------
I wouldn't have gotten rid of the error in line 22 so quickly. I should have known that a lot seems to have changed here.

![image](https://github.com/grimmpp/home-assistant-eltako/assets/46369917/1b9f1d09-6d82-4177-b57c-2ff6b62ed225)
![image](https://github.com/grimmpp/home-assistant-eltako/assets/46369917/42c8f46d-8b8a-497b-8480-ad928646a623)

Do you agree that this example is very outdated?
[Example Configuration File](https://github.com/grimmpp/home-assistant-eltako/blob/main/docs/update_home_assistant_configuration.md#example-configuration-file)

**Comment by cvanlabe** [comment]
Let me know if this is helpful or it needs more information. I think I covered all the required fields as I ran into all these things the hard way as well :-) https://github.com/cvanlabe/Eltako-home-automation/blob/main/README.md

**Comment by JDD-Home** [comment]
Thanks for your link. I will read it over the next few days. I have read through the article up to the "test bed". That could also be a contribution from me :D

**Comment by LHBL2003** [comment]
This issue is closed after a pull request from: https://github.com/grimmpp/home-assistant-eltako/pull/47
