### ISSUE TITLE
How to add new EEP devices

### ISSUE THREAD

**Issue by SteffenS27** [grimmpp/home-assistant-eltako#40]
Is it possible to install new EEPs?
For example, I have a motion sensor EEP A5-07-01 (Eltako FB65B) and a temperature/humidity EEP A5-04-01 (Nodon STPH-2-1-05)

**Comment by grimmpp** [comment]
Added in release v1.3.3:

https://github.com/grimmpp/home-assistant-eltako/releases/tag/v1.3.3-added-new-eep-A5-04-01-and-A5-07-01
