### ISSUE TITLE
FTS14EM - Visu (Status remains unknown):

### ISSUE THREAD

**Issue by LHBL2003** [grimmpp/home-assistant-eltako#43]
Hi, 
 
I can currently control FSR14_4x via home-assistant-eltako. 
Only for the FTS14EM I do not get the status displayed in HA.
I can do it in FHEM.
 
Upper rotary switch position: 10
Lower rotary switch position: UT 1
Port 5

<img src="https://github.com/grimmpp/home-assistant-eltako/assets/46369917/24b5b689-e203-49c2-ab4d-ae970df63d43" width=50% height=50%>

 
**Config**
```
eltako:
  gateway:
    - id: 1
      base_id: FF-00-00-00
      device_type: fgw14usb
      devices:
        binary_sensor:
        - id: 00-00-10-15
          eep: F6-02-01
          name: FTS14EM - KG-S1 - Signal 5 (Frei)
          #device_class: presence 
          #invert_signal: False
 
logger:
  default: info
  logs:
    eltako: debug
```
 
EEP: F6-02-01 is also set up by default in FHEM when FHEM scans the Eltako bus. 

Logging Message (It looks as if the signal is detected by HA.):

2024-01-15 20:25:52.653 DEBUG (Thread-2) [eltako] [Gateway] [Id: 1] Received message: <RPSMessage from 00 00 10 15, db0 = 70, status = 0x30 (T2, N, 0 repetitions)>
2024-01-15 20:25:52.656 DEBUG (SyncWorker_12) [eltako] [Binary Sensor] Send event: eltako.gw_1.btn_pressed.sid_00-00-10-15, pressed_buttons: '["RT"]'
2024-01-15 20:25:52.657 DEBUG (SyncWorker_12) [eltako] [Binary Sensor] Send event: eltako.gw_1.btn_pressed.sid_00-00-10-15.d_RT, pressed_buttons: '["RT"]'
2024-01-15 20:25:56.784 DEBUG (Thread-2) [eltako] [Gateway] [Id: 1] Received message: <RPSMessage from 00 00 10 15, db0 = 00, status = 0x20 (T2, U, 0 repetitions)>
2024-01-15 20:25:56.786 DEBUG (SyncWorker_23) [eltako] [Binary Sensor] Send event: eltako.gw_1.btn_pressed.sid_00-00-10-15, pressed_buttons: '[]'
2024-01-15 20:25:56.787 DEBUG (SyncWorker_23) [eltako] [Binary Sensor] Send event: eltako.gw_1.btn_pressed.sid_00-00-10-15.d_, pressed_buttons: '[]'
<img width="1428" alt="Bildschirmfoto 2024-01-15 um 20 27 18" src="https://github.com/cvanlabe/Eltako-home-automation/assets/46369917/d8fdcfb7-8ad3-47d1-b35b-97146453ac58">

Visu (Status remains unknown):
<img width="600" alt="Bildschirmfoto 2024-01-15 um 20 28 11" src="https://github.com/cvanlabe/Eltako-home-automation/assets/46369917/a8658d8d-fff1-4584-acb9-3e6e245924cc">

Do you have any idea what I should configure?

With eep: D5-00-01 it gets even worse.
<img width="1402" alt="Bildschirmfoto 2024-01-15 um 21 27 43" src="https://github.com/cvanlabe/Eltako-home-automation/assets/46369917/216b4e2a-7e5a-40d2-9164-7b2bc51e9c64">

**Comment by grimmpp** [comment]
Hello @LHBL2003, 

So now you can use for switch telegrams F6-02-01 and F-02-02 and for contact telegrams you can use D5-00-01. If it's wrongly configured the warning will tell you that message type and eep does not fit together.
I think in your case (FTS14EM) you can leave the configuration with eep F6-02-01.

**Comment by LHBL2003** [comment]
I get no signal in the visualization. Is there anything else I need to consider?
FTS14EM is set as shown Pic above. +E5 is triggered.

### Preparation
- Homeassistant is completely up-to-date.
- I deleted the HAC and downloaded it again to prevent any problems.
<img width="1626" alt="Bildschirmfoto 2024-01-19 um 20 15 59" src="https://github.com/grimmpp/home-assistant-eltako/assets/46369917/1dc2d4f2-50bc-420e-b661-7425632f3615">

-------------------

### Test 1

<img width="756" alt="Bildschirmfoto 2024-01-19 um 19 54 09" src="https://github.com/grimmpp/home-assistant-eltako/assets/46369917/cd9b9215-ea4e-4b05-9ed6-6545d94e9203">
<img width="1402" alt="Bildschirmfoto 2024-01-19 um 19 55 34" src="https://github.com/grimmpp/home-assistant-eltako/assets/46369917/f20b99c6-a7f9-473a-8b21-077aad1c91eb">
<img width="988" alt="Bildschirmfoto 2024-01-19 um 19 54 53" src="https://github.com/grimmpp/home-assistant-eltako/assets/46369917/a3fc7ff7-f5ff-4ebf-9ff1-4c1ad88b30ee">

-------------------

### Test 2
<img width="608" alt="Bildschirmfoto 2024-01-19 um 19 55 57" src="https://github.com/grimmpp/home-assistant-eltako/assets/46369917/98edf969-d75d-4d82-be19-74e126c1650e">
<img width="989" alt="Bildschirmfoto 2024-01-19 um 19 57 45" src="https://github.com/grimmpp/home-assistant-eltako/assets/46369917/78021cd9-4c98-45fe-bc36-1f5a5292153f">

<img width="989" alt="Bildschirmfoto 2024-01-19 um 19 57 45" src="https://github.com/grimmpp/home-assistant-eltako/assets/46369917/199fa453-72a0-47bf-aaf3-dbd93b42c7cd">

-------------------

### Test 3
<img width="635" alt="Bildschirmfoto 2024-01-19 um 20 01 15" src="https://github.com/grimmpp/home-assistant-eltako/assets/46369917/b31ad3a2-d4b2-443b-bb33-f4599f051873">
<img width="989" alt="Bildschirmfoto 2024-01-19 um 20 02 50" src="https://github.com/grimmpp/home-assistant-eltako/assets/46369917/8ae16cb7-6c87-480f-988a-dc8870b9b35d">
<img width="989" alt="Bildschirmfoto 2024-01-19 um 20 02 50" src="https://github.com/grimmpp/home-assistant-eltako/assets/46369917/d861ce90-0db3-4076-b131-ecc5a7d73068">

**Comment by LHBL2003** [comment]
Sorry the pictures for the test were not uploaded correctly. I have just updated it.

**Comment by grimmpp** [comment]
Hallo @LHBL2003,

can you test with newest release V1.3.4?

**Comment by LHBL2003** [comment]
Oh yes! You've found the problem ;)
I get a status (Rock)

<img width="1343" alt="Bildschirmfoto 2024-01-22 um 19 02 03" src="https://github.com/grimmpp/home-assistant-eltako/assets/46369917/3c800d70-9132-483f-bb52-3bdf19be27eb">

Well then I can start adding FHEM. That was the last interface point I was missing :)
Thank you very much for your help.

----------------------------

Perhaps this will help you to understand why the EM modules communicate so differently. In my case it says 13/17 on the back.

![IMG_9293](https://github.com/grimmpp/home-assistant-eltako/assets/46369917/639f256e-0225-4d45-9543-c0e41b42f8ee)
