### ISSUE TITLE
Support for ESP3 protocol so that USB300 transceiver can be used.

### ISSUE THREAD

**Issue by grimmpp** [grimmpp/home-assistant-eltako#66]
Currently ESP3 is in experimental state and shall be fully supported so that USB300 transceiver can be used.

Support from [alq.cev](https://community.home-assistant.io/u/alq.cev) was already provided:
https://community.home-assistant.io/t/eltako-baureihe-14-rs485-enocean-debugging/49712/271?u=philipp14

**Comment by peterhackenberg** [comment]
Hi,
can you maybe give a brief heads-up, what needs to be done to support the USB300 gateway?
Is it only about the ESP2 - ESP3 conversion?
Would like to help on this topic, hopefully I can.
Thanks!

**Comment by grimmpp** [comment]
Hey Peter,
I've started exploratory to integrate it. Incoming message can be processed. Sending messages is not working yet but I've already found the bug and I've already found out how it works technically and build it in into [enocean device manager](https://github.com/grimmpp/enocean-device-manager) yesterday night.
I've planned to clean it up and put it into the communication library [eltakobus](https://github.com/grimmpp/eltako14bus).

**Comment by peterhackenberg** [comment]
Nice work!
So I think you are already close to finishing this topic.
Really appreciate your work, exited to see the usb300 working.
If you need help, let me know.

**Comment by grimmpp** [comment]
Short update. It mainly works and is available on main branch. I personally have the issue that sending telegrams for EEP A5-38-08 is not recognized by my actuators. Not sure if this is an issue with USB300 or the actuator. Sad thing about it: It is required for switching on and off the lights with FUD and FSR :-(

**Comment by christophheich** [comment]
@grimmpp i will switch my local version to this one after the final USB300 release has been completed.

I am gonna write a small tutorial for the USB300 with the explanation about the CRC8 checksum and the combination of each hexadecimal value if you don’t mind. Just for reference.
