### ISSUE TITLE
Sensors like FABH65 or FBH65TF only support motion but no brightness

### ISSUE THREAD

**Issue by Pegasus500** [grimmpp/home-assistant-eltako#69]
Sensors using the A5-08-01 only show the motion entity in HA, the brightness value is missing. Could this be added somehow?
Also, it would be very nice to see the voltage value for these battery or solar operated sensors. 
I could help with the telegram info of Eltako but I have no clue how to implement this here.

Funk-Telegramme nach EEP A5-08-01
(Exceptions by Eltako)
Helligkeitsbereich erweitert, kein Occupancy
Button im DB0_Bit0)
ORG = 0x07
Data_byte3 = Betriebsspannung 0..5,1 V
(0..255)
Data_byte2 = Helligkeit 0..510 lux (0..255)
Data_byte1 = -
Data_byte0 = 0x0D = Bewegung
0x0F = keine Bewegung
Lerntelegramm: 0x20080D85

**Comment by grimmpp** [comment]
Hello @Pegasus500,

jup, that's quite easy and actually already available but not displayed.

**Comment by Pegasus500** [comment]
Could you make those values visible? I tried moving the sensor from binary sensor to sensors and adding illuminance, but I could not get a valid configuration. BTW, your Eltako integration is appreciated very much, thank you!

**Comment by grimmpp** [comment]
Thanks,  yes that's what I meant I will do it. Before that I need to fix the cover/shutters. I broke them by introducing the state recovery feature which shows you the values before restarting HA after you restarted it.

**Comment by grimmpp** [comment]
Hello @Pegasus500,
can you please send me an example telegram for testing?

**Comment by Pegasus500** [comment]
In PCT14 I get: 0x05,5 FF BA BE 80 DB3: 0x70
Is there a better way to get the raw telegrams?

**Comment by grimmpp** [comment]
I need to check if it is sufficient.

Because development and testing in HA is very inconvenient, I'm about to develop an independent app which also allows you to inventory, describe, manage your devices + generate HA config automatically. 
If you are interested in, it would be nice to get feedback if you can use it for managing your devices and generating HA config. You can also receive telegram after you have connected a gateway. FAM14, FGW14-USB, FAM-USB and USB300 are already supported. After you received the first telegram the device is displayed in the table and you can assign the EEP. When further telegrams are received it will show the values corresponding to the EEP in addition. You can also change the EEP in between. 
Unfortunately, you need to wait always for new incoming telegram after you change EPP but I've planned to change that.

https://github.com/grimmpp/enocean-device-manager

**Comment by Pegasus500** [comment]
I tried the app und it looks very promising. But after selecting "detect COM" or selecting FAM-USB I always get "established serial connection" and "ERROR write timeout". This happens after installing in a virtual environment or directly under Windows.

**Comment by grimmpp** [comment]
I don't understand what the data is of the telegram you've sent earlier. For me it looks like that only data_byte3 is available. I need all 4 from 0 to 3. You could also enable debug logs for the integration and check the logs. And then search for the telegram of your address: FF BA BE 80

Here at the end of the config you see how to switch debug logs on.
https://github.com/grimmpp/home-assistant-eltako/blob/main/docs/update_home_assistant_configuration.md

**Comment by Pegasus500** [comment]
Ok, I think I got some better telegrams now:

FBH65TF #1:
DEBUG (Thread-2) [eltako] [Gateway] [Id: 1] Received message: <RPSMessage from ff ba be 80, db0 = 70, status = 0x30 (T2, N, 0 repetitions)>
DEBUG (Thread-2) [eltako] [Gateway] [Id: 1] Received message: <Regular4BSMessage from ff ba be 82, data aa 00 00 0d, status = 0x00>
DEBUG (SyncWorker_53) [eltako] decoded : {"_supply_voltage": 3.3999999999999995, "_illumination": 0.0, "_temperature": 0.0, "_learn_button": 1, "_pir_status": 0, "_occupancy_button": 1}
DEBUG (Thread-2) [eltako] [Gateway] [Id: 1] Received message: <Regular4BSMessage from ff ba be 81, data aa 80 76 0f, status = 0x30>

FBH65TF #1:
DEBUG (Thread-2) [eltako] [Gateway] [Id: 1] Received message: <RPSMessage from ff 9d a0 80, db0 = 70, status = 0x30 (T2, N, 0 repetitions)>
DEBUG (Thread-2) [eltako] [Gateway] [Id: 1] Received message: <Regular4BSMessage from ff 9d a0 82, data b6 00 00 0d, status = 0x00>
DEBUG (SyncWorker_53) [eltako] decoded : {"_supply_voltage": 3.6399999999999997, "_illumination": 0.0, "_temperature": 0.0, "_learn_button": 1, "_pir_status": 0, "_occupancy_button": 1}
DEBUG (Thread-2) [eltako] [Gateway] [Id: 1] Received message: <Regular4BSMessage from ff 9d a0 81, data b6 87 76 0f, status = 0x30>

FABH65:
DEBUG (Thread-2) [eltako] [Gateway] [Id: 1] Received message: <Regular4BSMessage from 05 2b 40 0c, data cb 00 00 0d, status = 0x01>
DEBUG (SyncWorker_44) [eltako] decoded : {"_supply_voltage": 4.06, "_illumination": 0.0, "_temperature": 0.0, "_learn_button": 1, "_pir_status": 0, "_occupancy_button": 1}

**Comment by grimmpp** [comment]
Oh, man. I don't like exceptions from the standard. Good think about it is, it is already implemented this way. :-)
![image](https://github.com/grimmpp/home-assistant-eltako/assets/12120359/a9ff9b97-833f-43d2-a2cd-41dfc02b8d8b)

Good to know what device you are using. It looks like FBH65TF has 3 addresses (in your case: ff ba be 80, ff ba be 81, ff ba be 82) and you get status update, A5-08-01 and A5-04-02. In that case we just need to display the entities. Personally I tend to display many separate devices. Actually FBH65TF is also a many in one. One the dashboards you could group the entities in a way that it look like one device if you like or use the name in the config that should group the entities together into one device.

**Comment by grimmpp** [comment]
In your example I haven't found the telegrams for A5-04-02. 
A5-08-01 is supported now and available under main. **Would be cool if you could test it and compare if the displayed values make sense.**
For your example data = 0xAA80760F it would look like: 
![image](https://github.com/grimmpp/home-assistant-eltako/assets/12120359/5fb32828-2d90-4b32-b440-3d5b257fa749)
A5-04-02 would look like this:
![image](https://github.com/grimmpp/home-assistant-eltako/assets/12120359/13a8b458-d89c-4de0-8c1d-6745178bb38e)

**Comment by Pegasus500** [comment]
Here is one of my sensors after I copied the binary sensors into sensors as well (in configuration.yaml).
![Screenshot_2024-02-26-12-12-27-340_io homeassistant companion android-edit](https://github.com/grimmpp/home-assistant-eltako/assets/72942489/27017252-b4f5-430e-8803-0ee301c9e35a)
![Screenshot_2024-02-26-12-12-08-544_io homeassistant companion android-edit](https://github.com/grimmpp/home-assistant-eltako/assets/72942489/f4adac2a-819a-461e-ba20-3e36af8ca301)

The values for humidity and temperature look okay (I already had them before), voltage fits also. The illuminance however seems too low, exactly a factor 3 compared wirh the FHEM integration.
In the motion sensor there is a temperature entity which is too much.
Thank you very much for the effort.

**Comment by grimmpp** [comment]
Regarding temperature: Is is part of the EEP and depends on the sensor if you get a value or not. Same with the other entities. You can just remove unused entities on your dashboard.
Regarding illuminance: I took the range Eltako specified. Do you know by accident what range is used by FHEM?
![image](https://github.com/grimmpp/home-assistant-eltako/assets/12120359/0d7881f2-e1d1-41c2-a104-0c94d0cb2b62)

**Comment by grimmpp** [comment]
Hello @Pegasus500,

I've found the code and FHME distinguishes in case of A5-08-01 between devices:
All starting with FB data*2 and others data*8
https://svn.fhem.de/fhem/trunk/fhem/FHEM/10_EnOcean.pm
![image](https://github.com/grimmpp/home-assistant-eltako/assets/12120359/63f78a76-bdd8-444d-be36-2b864303e0b0)

**Comment by grimmpp** [comment]
for easier debugging I've added a EEP Checker in [eo-man](https://github.com/grimmpp/enocean-device-manager):
![image](https://github.com/grimmpp/home-assistant-eltako/assets/12120359/40395540-cef3-4c48-a4c3-020f8c1c9d15)
